export const serverCallUrls = {
  cardClaim: `/cards/claim`,
  spend: (code: string) => `/cards/${code}/spend`,
  userExists: `/users/exists`,
  sendShortCode: `/users/send/short-code`,
  registerVendor: `/users/create/business`,
  registerUser: `/users/create`,
  login: `/auth/login`,
  getUsers: `/users`,
  getListOfBanks: `/payment/list-of-banks`,
  resetPassword: `/users/resetPassword`,
  forgetPassword: `/users/forgotPassword`,
  saveTransaction: `cards/save-transaction`,
  createCard: `/cards/create`,
  triggerCardCreation: `/cards/triggerCreation`,
  getCards: (status: string) => `/cards/${status}`,
  updateUserDetails: `/users/update`,
  getAccountName: `/payment/get-account-name`,
  getVendorStats: `/vendor/stats`,
  getVendorTransactions: `/vendor/transactions`,
  uploadProfileImage: `users/update/pic`,
};
